### ISSUE TITLE
是否可以使用 cross-env 来解决 window 平台的问题

### ISSUE THREAD

**Issue by yydounai1234** [ryuujo1573/qnweb-rtc-demo#8]
https://github.com/ryuujo1573/qnweb-rtc-demo/blob/7657acc4629a5ace42fb2d48518a2265e0da44f5/package.json#L8-L10

**Comment by ryuujo1573** [comment]
使用 pnpm + pwsh + cross-env 在 Windows 环境下会出现失去响应的问题；
临时排查后可以通过使用 bash 并设置 pnpm 解决
```
pnpm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"
```
<details>
<summary>补充信息</summary>

https://github.com/kentcdodds/cross-env/issues/192#issuecomment-513341729
 这部分环境变量的设置在 GitHub Pages 上构建时有问题，后续尝试通过其他方式传递构建时间的元信息

</details>
