### ISSUE TITLE
[style] unify naming conventions

### ISSUE THREAD

**Issue by yydounai1234** [ryuujo1573/qnweb-rtc-demo#9]
https://github.com/ryuujo1573/qnweb-rtc-demo/blob/2416bc791a4bc12fb42a54781c90f82b03b2ba27/src/components/DetailPanel.tsx#L106

**Comment by ryuujo1573** [comment]
关于这部分命名是应该将 `视频轨道 / 音频轨道` 改写成 `视频轨 / 音轨` 吗
